### ISSUE TITLE
Yarkovsky effect in Reboundx : question about the 'k' coefficient

### ISSUE THREAD

**Issue by PK-ReboundX** [dtamayo/reboundx#103]
This time, my question is more scientific than technical....
I tried to compare the Yarkovsky effect implemented in Reboundx with other computing packages and a problem arose, which I will describe below.

In most methods, the following parameters are used to simulate this effect:

(1) radius, (2) surface and mean densities , (3) thermal conductivity - kappa, (4) thermal capacity - C , (5) albedo, (6) infrared emissivity (epsilon) , (7) rotation period (8) Spin axis coordinates  

In Reboundx the parameters set is similar, but not the same (full effect):

(1) radius, (2) mean density , (3) Gamma (containing information on surface density, thermal conductivity and thermal capacity), (4) albedo, (5) infrared emissivity (epsilon) , (6) rotation period (7) Spin axis coordinates 

Additional element in Reboundx is (8) 'k' coefficient. As I found in the papers cited, it varies from zero (fast rotation) to 0.25 (rotation close to the orbital period), but no function/formula is described to calculate it.  The question is: how can it be reliably estimated?

In most examples it is set to 0.25, which in my opinion gives an overestimated (too large) drift in 'a'. 

Is it sufficient to assume that it varies linearly with the rotation period?

Thanks in advance for any suggestions,

Regards,

PK

**Comment by Nofe4108** [comment]
I will try and paraphrase what Dimitri Veras, the lead author of those cited papers, told me about the parameter 'k'. 

The spin of asteroids and other small bodies is often chaotic and not easily deterministic. Therefore, they added the constant 'k' as a way to avoid taking into account the complex spin behavior of an object in their Yarkovsky effect model. In theory, 'k' should change at every timestep due to YORP and other factors that are affecting the spin of the object. 

We kept 'k' at 0.25 in our examples just to simplify things. You can consider those results as upper bounds on the motion of those particles. I think having 'k' depend linearly with the rotation period is a completely sufficient low-order approximation as long as you have those two endpoints calculated correctly. 

Hope this helps. If you have more questions or want more details, I would try reaching out to to Dr. Veras for a more satisfying answer.

**Comment by PK-ReboundX** [comment]
Thank you for your reply,

A thorough comparison of the model and parameters used gives some sort of falsification.I think that specialists who want to change the tool to the Reboundx module will first thoroughly test whether it gives reliable results.

For my part, I can say that I have started tests with asteroids for which I already have Yarkovsky drift results obtained with the RMVSY tool (Broz, 2006).
For one of them I scaled the 'k' value linearly and finally obtained a similar drift in semimajor axis after 1M years. This looks very promising, but I need to test more complicated examples with the original spin axis solutions.

P. S. I hope that the tool will develop with other non-gravitational effects, in new modules (e.g. cometary accelerations)

Regards,

PK
