### ISSUE TITLE
Acceleration Output as 0 when integrating with REBOUNDx

### ISSUE THREAD

**Issue by rosecolinlarry** [dtamayo/reboundx#31]
I have found once adding an additional force effect with REBOUNDx, after integrating the accelerations are output to be 0.

For example, this correctly outputs an acceleration before integrating with the additional force, but outputs 0.0 for the accelerations after adding the force and integrating. (Base code from this tutorial https://github.com/dtamayo/reboundx/blob/master/ipython_examples/GeneralRelativity.ipynb)

```python
import rebound
sim = rebound.Simulation()
sim.add(m=1., hash="star") # Sun
sim.add(m=1.66013e-07,a=0.387098,e=0.205630, hash="planet") # Mercury-like
sim.move_to_com() # Moves to the center of momentum frame
ps = sim.particles

print("Initial acceleration in x direction should be 0:  ", ps[1].ax)
sim.integrate(10.)
print("Acceleration in x direction after first integration should not be 0:  ", ps[1].ax)
print("pomega = %.16f"%sim.particles[1].pomega)

import reboundx
rebx = reboundx.Extras(sim)
gr = rebx.add("gr")

from reboundx import constants
gr.params["c"] = constants.C

ps["star"].params["gr_source"] = 1

print("Acceleration in x direction after adding gr should not be 0:  ", ps[1].ax)

deltat = 100.
E0 = rebx.gr_hamiltonian(sim, gr)
sim.integrate(sim.t + deltat)
Ef = rebx.gr_hamiltonian(sim, gr)
print("Acceleration in x direction after adding gr and integrating should not be 0 but will be:  ", ps[1].ax)

print("pomega = %.16f"%sim.particles[1].pomega)
juliancentury = 628.33195 # in yr/2pi
arcsec = 4.8481368e-06 # in rad
print("Rate of change of pomega = %.4f [arcsec / Julian century]"% (sim.particles[1].pomega/deltat*juliancentury/arcsec))
print("Relative error on the relativistic Hamiltonian = {0}".format(abs(Ef-E0)/abs(E0)))
```

How would one get the acceleration info of the particles post integration?

Thanks!

Best,
Kaisa

**Comment by hannorein** [comment]
Hi Kaisa, 

The accelerations are only used internally to calculate the trajectory. You can print out the forces in a custom `additional_forces` function (however, that won't work when you use REBOUNDX). Why do you read the forces? I assume it's for debugging?

Hanno

**Comment by dtamayo** [comment]
Like @hannorein says, they're only used internally and in some cases it doesn't make sense to look at them after a timestep. In a splitting method, a subset of the accelerations are calculated with intermediate positions and velocities, so they don't have any physical meaning at the end of the timestep, just the final positions and velocities. That said, I have changed the logic so that in cases where there are no split operators, it doesn't reset the accelerations to 0. So in the case 
you posted above, it would output the accelerations. I've pushed the new version (2.19.3) to the master branch, along with a new RK2 integrator option.

Note that the gr implementation you're using above is velocity dependent, and can give spurious results in long-term integrations. You either want to use "gr_potential", or if you use "gr", you want to use gr.force_as_operator=1 so that you integrate the velocities across the timestep. Hope that helps! Feel free to reopen if you have any follow-up questions.

**Comment by rosecolinlarry** [comment]
We are analyzing the affects of radiation pressure on a satellite and like
to output accelerations at the same integration time steps. We output the
velocity, coordinates, time steps, and sim times for 100 points per
satellite orbit. We would like to output the same amount at the same
simulation times for accelerations to compare acceleration against other
factors.

However, as I understand it, we can't do that with ReboundX and have to do
it with Rebounds add additional force?

Best,
Kaisa

**Comment by hannorein** [comment]
No, Dan has updated REBOUNDX so you should be able to print out the acceleration after each timestep! Just update REBOUNDX to the latest version.

**Comment by dtamayo** [comment]
If you want precise accelerations, you probably want to use the IAS15 integrator like you do in the snippet above (implicitly, since that's the default integrator). Like Hanno mentioned above, the accelerations are in general meant to be used internally...for example for the WHFast integrator, the accelerations are evaluated in the 'middle' of the timestep. So if you care about exact values, you need to understand what the particular integrator is doing. If you're using IAS15 I think you should be fine. @hannorein can correct me!

I also just pushed the new version to PyPI. If you installed with pip install reboundx you can update with pip install reboundx --upgrade
